# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Proect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Proect

   pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

pod 'Alamofire'
pod 'SwiftyJSON', '~> 4.0'


pod'LTMorphingLabel',:git=>'https://github.com/lexrus/LTMorphingLabel',:branch => 'master'
end
